name: metabolic
channels:
- conda-forge
- defaults
dependencies:
- bokeh==1.4
- bottleneck
- cartopy
- cf_units
- cftime
- cmocean
- conda-lock
- dask==2.14
- distributed==2.14
- dask-jobqueue=0.7.1
- dask-mpi
- eofs
- esmpy
- holoviews
- intake
- intake-esm
- ipykernel
- jupyter-server-proxy
- jupyter_contrib_nbextensions
- jupyterlab
- lmfit
- matplotlib
- metpy
- nc-time-axis
- ncar-jobqueue
- netcdf4
- numba
- numpy
- pandas=1.2.5 # pinned to avoid indexing error: ds.sel(time=slice('1920', '2100'))
- pint
- pip
- pop-tools
- pytest
- python
- scipy
- seaborn
- seawater
- statsmodels
- toolz
- tqdm
- watermark
- xarray
- xesmf
- xgcm
- xhistogram
- xrft
- zarr
